title:              Soloviov Blog🇺🇦
email:              vany.soloviov@gmail.com
description:        This is my blog on IT theme and more.
author:             Soloviov Ivan
baseurl:           
url:               "https://www.soloviov.fun/"
enforce_ssl: www.soloviov.fun

# Social Profiles
twitter_username:   
github_username:    WarmingZ
facebook_username:  Soloviov.IA
instagram_username:  warmiddle/
linkedin_username:   ivan-soloviov-62403b193
telegram_username:   SoloviovIA

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-211989430-1 

markdown: kramdown
highlighter: rouge

# Build settings
markdown: kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
  - jekyll-seo-tag
  - jekyll-feed
permalink: /:categories/:title/

gem: [jekyll-admin]

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: https-warmingz-github-io
